export enum ProjectType {
  ESTIMATE_REVIEW = "ESTIMATE_REVIEW",
  PROPOSAL_REVIEW = "PROPOSAL_REVIEW",
  CONTRACT_REVIEW = "CONTRACT_REVIEW",
  MEETING_SUMMARY = "MEETING_SUMMARY",
  GENERAL_ANALYSIS = "GENERAL_ANALYSIS"
}
